[package]
name = "raytracer"
version = "0.1.0"
authors = ["ChinYing-Li <chinying.li@mail.utoronto.ca>"]
edition = "2018"

[dependencies]
approx = "0.3.2"
enum-set = "0.0.8"
image = "0.23.7"
rand = "0.7.3"
cgmath = "0.17.0"
obj = "0.10.1"
